---
title: "Voting habits in elections based on states and surrounding context"
author: "Sawyer Wedin"
date: "2025-11-25"
output: html_document
---

```{r}
library(readr)
anesVoterDat <- read.csv("~/PSY-4802-Final-Project/anes_timeseries_2024_csv_20250808.csv", header=FALSE)
View(anesVoterDat)
```

```{r}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(viridis)
library(tidyr)
```

```{r}
#Rows here are listed as participants. One of the survey questions is which state they are registered to vote in, so I think it is safe to use that as what state they are "in".
#First I sectioned out the columns I'm interested in.
smallAnesVoterDat<- anesVoterDat %>% 
  select(V2, V52, V61, V62, V64, V70, V71, V72, V78, V93, V105, V909, V910, V916, V919, V920, V924, V926, V927, V930)
view(smallAnesVoterDat)

#Next, I renamed the columns to something more understandable. Columns with the "pre" prefix include answers given before voting. I removed the top column, which contained the column names as seen in th Excel file (which have now become redundant and interfere with the data). Then I replaced negative numbers with NA values.
names(smallAnesVoterDat)<- c("Participant", "registeredVoter", "sampleState", "registeredState", "registeredParty", "primaryVoter", "demPrimary", "repPrimary", "prePresVote", "preHouseVote", "preSenateVote", "presVote", "presCandidate", "presPref", "houseVote", "houseParty", "housePartyPref", "senateVoted", "senateParty", "senatePartyPref")
#sampleState is just asking if the state they reside in matches the state they vote in.
cleanerAnesDat<- smallAnesVoterDat[-c(1),]
cleanerAnesDat$statePresVote<- cleanerAnesDat$registeredState
cleanerAnesDat[cleanerAnesDat==-1]<- NA


cleanAnes<- cleanerAnesDat %>% select(-registeredVoter)
cleanAnes$statePresVote2<- factor(cleanAnes$statePresVote, levels=c("1", "2", "4", "5", "6", "8", "9", "10", "11", "12", "13", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "44", "45", "46", "47", "48", "49", "50", "51", "53", "54", "55", "56"), labels=c("2", "2", "2", "2", "1", "1", "1", "1", "1", "2", "2", "1", "2", "1", "2", "2", "2", "2", "2", "1", "1", "1", "2", "1", "2", "2", "2", "2", "2", "1", "1", "1", "1", "2", "2", "2", "2", "1", "2", "1", "2", "2", "2", "2", "2", "1", "1", "1", "2", "2", "2"))
```

1. Are voters likely to vote congruent to the state they are registered to vote in?
```{r}
cleanAnes$congruent <- ifelse(cleanAnes$presCandidate==cleanAnes$statePresVote2, 1, 0)
cleanAnes$presCandidate[cleanAnes$presCandidate==-6]<- NA
cleanAnes$presCandidate[cleanAnes$presCandidate==-7]<- NA
cleanAnes$presCandidate[cleanAnes$presCandidate==-8]<- NA
cleanAnes$presCandidate[cleanAnes$presCandidate==-9]<- NA
cleanAnes$presCandidate<- factor(cleanAnes$presCandidate, levels = c("1", "2", "4", "5", "6"), labels = c("D", "R", "Other", "Other", "Other"))
cleanAnes$statePresVote2<- factor(cleanAnes$statePresVote2, levels = c("1", "2"), labels = c("D", "R"))
summary(glm(formula = congruent~statePresVote2+presCandidate, family = "binomial", data=cleanAnes))

cleanAnes$congruent2<- factor(cleanAnes$congruent, levels = c("0", "1"), labels = c("Incongruent", "Congruent"))
ggplot(data = subset(cleanAnes, !is.na(statePresVote2)), aes(statePresVote2, fill = presCandidate))+
  theme_bw()+
  geom_bar()+
  facet_wrap(~congruent2)+
  ggtitle("Congruency of Voters with State")+
  xlab("Electoral College Vote in State")+
  ylab("Number of Participants")
```

2. Are party registration frequencies more likely than chance?
```{r}
#Setting up
levels(as.factor(cleanAnes$registeredParty))
cleanAnes$registeredParty[cleanAnes$registeredParty==-8]<- NA
cleanAnes$registeredParty[cleanAnes$registeredParty==-9]<- NA
cleanAnes$registeredParty[cleanAnes$registeredParty==4]<- NA
summary(cleanAnes$registeredParty)
cleanAnes$registeredParty<- as.numeric(cleanAnes$registeredParty)
levels(as.factor(cleanAnes$registeredParty))

#I got this far, then realized it doesn't want to let me run a test on specific columns. So we must make another matrix!
cleanAnes$democratMember<- ifelse(cleanAnes$registeredParty==1, 1, 0)
cleanAnes$republicanMember<- ifelse(cleanAnes$registeredParty==2, 1, 0)
cleanAnes$otherParty<- ifelse(cleanAnes$registeredParty==5, 1, 0)

anesPartyMemberDat<- matrix(c(cleanAnes$democratMember, cleanAnes$republicanMember, cleanAnes$otherParty), ncol = 3)
colnames(anesPartyMemberDat)<- c("Democrat", "Republican", "Other")

chisq.test(na.omit(anesPartyMemberDat)) #X-squared = 3970, df = 3968, p-value = 0.4881

cleanAnes$registeredParty2<- factor(cleanAnes$registeredParty, levels = c("1", "2", "5"), labels = c("Democrat", "Republican", "Other"))
cleanAnes$registeredParty2[cleanAnes$registeredParty2==NA]<- "No Data"
ggplot(cleanAnes, aes(registeredParty2, fill = presCandidate))+
  geom_bar()+
  theme_bw()+
  ggtitle("Party Affiliation")+
  xlab("Party")+
  ylab("Number of Participants")
```

3. What elections are voters most likely to participate in?
```{r}
#mcnemar.test
#First, the Senate vote
levels(as.factor(cleanAnes$senateVoted))
cleanAnes$senateVoted[cleanAnes$senateVoted==-5]<- NA
cleanAnes$senateVoted[cleanAnes$senateVoted==-7]<- NA
cleanAnes$senateVoted[cleanAnes$senateVoted==-6]<- NA
cleanAnes$senateVoted<- as.factor(cleanAnes$senateVoted)
is.factor(cleanAnes$senateVoted)
summary(cleanAnes$senateVoted) #Here, 1 = D and 2 = R

#Now, the House vote
levels(as.factor(cleanAnes$houseVote))
cleanAnes$houseVote[cleanAnes$houseVote==-5]<- NA
cleanAnes$houseVote[cleanAnes$houseVote==-7]<- NA
cleanAnes$houseVote[cleanAnes$houseVote==-6]<- NA
cleanAnes$houseVote<- as.factor(cleanAnes$houseVote)
is.factor(cleanAnes$houseVote)
summary(cleanAnes$houseVote) #Here, 1 = D and 2 = R

# This is my best guess for figuring out how to set this up?
cleanAnes$bothHouseSenate<- ifelse(cleanAnes$houseVote==1 & cleanAnes$senateVoted==1, 1, 0)
cleanAnes$bothHouseSenate<- as.factor(cleanAnes$bothHouseSenate)
cleanAnes$onlyHouse<- ifelse(cleanAnes$houseVote==1 & cleanAnes$senateVoted==2, 1, 0)
cleanAnes$onlyHouse<- as.factor(cleanAnes$onlyHouse)
cleanAnes$onlySenate<- ifelse(cleanAnes$senateVoted==1 & cleanAnes$houseVote==2, 1, 0)
cleanAnes$onlySenate<- as.factor(cleanAnes$onlySenate)
cleanAnes$noHouseSenate<- ifelse(cleanAnes$senateVoted==2 & cleanAnes$houseVote==2, 1, 0)
cleanAnes$noHouseSenate<- as.factor(cleanAnes$noHouseSenate)

#Now to figure out what my matrix is going to look like
summary(cleanAnes$bothHouseSenate)
summary(cleanAnes$onlyHouse)
summary(cleanAnes$onlySenate)
summary(cleanAnes$noHouseSenate)

#Assembling the matrix
anesSenateHouse<- c(2418, 37, 98, 149)
anesSenateHouseMatrix<- matrix(anesSenateHouse, ncol = 2)
colnames(anesSenateHouseMatrix)<- c("Voted in House", "Did Not Vote in House")
rownames(anesSenateHouseMatrix)<- c("Voted in Senate", "Did Not Vote in Senate")
mcnemar.test(anesSenateHouseMatrix) #McNemar's chi-squared = 26.667, df = 1, p-value = 2.418e-07

print(anesSenateHouseMatrix)
```

